### PR TITLE
Update file name

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Comment by Gowixx** [comment]
reasoning?

**Comment by KendallDoesCoding** [comment]
Most coders name their files as follows:

HTML - index.html
CSS: style.css/styles.css
JS: script.js/index.js

**Comment by Gowixx** [comment]
Honestly, I don't really mind how it is right now.

**Comment by KendallDoesCoding** [comment]
> Honestly, I don't really mind how it is right now.

neither do i,  it was just a suggestion but comes to the same thing

**Pull request closed without merging**
